name 'mburger-rundeck'
version '2.0.11'

author 'Markus Burger'
license 'Apache2'
source 'https://github.com/mburger/puppet-rundeck'
summary 'Puppet module for rundeck'
description 'This module installs and manages rundeck. Check README for details.'
dependency 'example42/puppi', '>=2.0.0'
dependency 'example42/firewall', '>=2.0.0'
dependency 'example42/monitor', '>=2.0.0'
